id = "al"
name = "AL"
version = "0.0.2"
schema_version = 1
authors = ["Barne-B", "rznd"]
description = "AL language support for Zed"
repository = "https://github.com/rznd/zed-al"
snippets = "snippets/al.json"

[grammars.al]
repository = "https://github.com/SShadowS/tree-sitter-al"
rev = "3e4ccb672f27d1ad673a8a995b1f5c770bb0f738"

[language_servers.al]
name = "AL Language Server"
languages = ["AL"]

[slash_commands.al-next-id]
description = "finds the next free AL ID in a file or object"
requires_argument = true
